# Generated by Django 5.2.4 on 2025-08-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='delivery_charge',
        ),
    ]
