# Generated by Django 5.2.4 on 2025-08-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='option',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
