# Generated by Django 5.2.4 on 2025-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderlineitem_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='option',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
