# Generated by Django 5.2.4 on 2025-08-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoaction',
            name='product_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
