# Generated by Django 5.2.4 on 2025-09-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemaster',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
